### ISSUE TITLE
data

### ISSUE THREAD

**Issue by Lj4040** [Chunngai/gec-datasets#1]
NUCLE data set has not been downloaded successfully. Could you share it with me?

**Comment by Chunngai** [comment]
@Lj4040 Hello. The NUCLE data can be obtained by following the instructions in [the CoNLL2014 website](https://www.comp.nus.edu.sg/~nlp/conll14st.html).

**Comment by Lj4040** [comment]
I have tried the form of this link for several times, but no link has been sent to me. I don't know why

**Comment by Lj4040** [comment]
May I have your contact information? Can you share it with me? Thank you very much, if that's convenient

**Comment by Chunngai** [comment]
@Lj4040 I'm afraid that the data can not be shared, as clearly stated in the license form. Have you strictly follow the filling requirements [here](https://sterling8.d2.comp.nus.edu.sg/nucle_download/nucle.php)? The data will be sent to you via email.

**Comment by Lj4040** [comment]
Thank you for your answer
