### ISSUE TITLE
Structure of Data

### ISSUE THREAD

**Issue by saramoeini20** [Chunngai/gec-datasets#2]
Hi,
I have a question regarding dataset. In first Step You changed M2 format to source/target (parallel) file, right?
Do we need just this format for GEC models or both of them? I'm at beginning of GEC and i would be grateful if you could help me.

**Comment by Chunngai** [comment]
Hello.

Generally, GEC is treated as a translation task, where the source is the erroneous sentence and the target is the correct sentence. So only the parallel data are needed for GEC training. 

But you can also make use of the M2 information for enhancing correction performance.

**Comment by saramoeini20** [comment]
So if we use translation task for GEC we need parallel data, but what about other methods? for which kind of models we need M2 format?
And what should be the format for test data?
Actually I wanted to make dataset for training and test myself and was kind of confused

**Comment by Chunngai** [comment]
Most GEC models in recent years use parallel GEC data for training. I haven't seen one directly receiving the M2 data.

Test data are also parallel. The trained model receives the source data and outputs predictions. The predictions are then compared with the target data with evaluation tools, such as m2scorer and errant.

**Comment by saramoeini20** [comment]
thank you so much
